### ISSUE TITLE
 Error: None zero returncode - biom.exception.TableException: Unsupported matrix data type.

### ISSUE THREAD

**Issue by ckeuschn** [hsgweon/pipits#33]
Hi

I installed pipits on macOS mojave as well as on a linux cluster, but I run into a similar problem, when testing on the included test files, as reportet here  #20. Changing the local to en_US.UTF-8 could not solve the problem...
 

2019-05-26 18:17:44 Converting classic tabular OTU into a BIOM format [BIOM]
Traceback (most recent call last):
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/home/ampere/ckeuschn/anaconda3/envs/pipits_env/lib/python3.6/site-packages/biom/table.py", line 4278, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.
2019-05-26 18:18:01 Error: None zero returncode: biom convert -i out_process/intermediate/otu_table_prelim.txt -o out_process/intermediate/otu_table_prelim.biom --table-type="OTU table" --to-json

Any help is appreciated
Thanks

**Comment by hsgweon** [comment]
Sorry @ckeuschn
Thanks for letting me know about this. I'm resolving it at the moment (it's mostly done actually). I will let you know when this has been fixed and conda package has been updated.

**Comment by ckeuschn** [comment]
Great thanks a lot!

**Comment by hsgweon** [comment]
All done. Can you please remove pipits_env and try all again? You can remove the previous env by:
`conda remove --name pipits_env --all` Please do let me know how it goes?

**Comment by ckeuschn** [comment]
I uninstalled and installed pipits as you told and after setting locale to en_US.utf8 everything worked without problems in the test directory.
Thanks for the quick support!

**Comment by hsgweon** [comment]
Perfect. Good luck with your analyses and if you need any help regarding PIPITS, do let me know.
