### ISSUE TITLE
unable to download UNITE trained database, version: 27.10.2022

### ISSUE THREAD

**Issue by JavariaAshraf** [hsgweon/pipits#56]
Hi PIPITS team,
I am on the last step of pipits pipeline:
`pipits_process -i out_funits/ITS.fasta -o out_process -v -r`
WHILE Downloading UNITE trained database, version: 27.10.2022
It gives error that the` Downloaded data is corrupt. Get in touch with PIPITS team!. Exiting...`
Kindly guide how to solve this issue.

Thank you,
Javaria

**Comment by mhfDK95** [comment]
Dear PIPITS team, 
I think I have an error at the same step (step B3. Process sequences) but I get a different error statement:

pipits_process -i out_funits/ITS.fasta -o out_process
pipits_process 3.0, the PIPITS Project
https://github.com/hsgweon/pipits
---------------------------------

2023-07-26 11:31:07 pipits_process started
2023-07-26 11:31:07 Generating a sample list from the input sequences
2023-07-26 11:31:07 Downloading UNITE trained database, version: 27.10.2022
Traceback (most recent call last):
  File "/home/cbn278/anaconda3/envs/pipits_env/bin/pipits_process", line 357, in <module>
    verbose = options.verbose)
  File "/home/cbn278/anaconda3/envs/pipits_env/bin/pipits_process", line 259, in downloadDB
    import progressbar
  File "/home/cbn278/anaconda3/envs/pipits_env/lib/python3.6/site-packages/progressbar/__init__.py", line 3, in <module>
    from .utils import (
  File "/home/cbn278/anaconda3/envs/pipits_env/lib/python3.6/site-packages/progressbar/utils.py", line 9, in <module>
    from python_utils.time import timedelta_to_seconds, epoch, format_time
  File "/home/cbn278/anaconda3/envs/pipits_env/lib/python3.6/site-packages/python_utils/__init__.py", line 1, in <module>
    from . import (
  File "/home/cbn278/anaconda3/envs/pipits_env/lib/python3.6/site-packages/python_utils/converters.py", line 89
    if match := regexp.search(input_):
              ^
SyntaxError: invalid syntax

Hope you can help.

All the best,
Marie

**Comment by ndusek** [comment]
I am seeing the same issue as Marie, from line 89 in `converters.py`:

```
    if match := regexp.search(input_):
              ^
SyntaxError: invalid syntax
```

Running PIPITS v3.0.

**Comment by hsgweon** [comment]
@mhfDK95 and @ndusek Sorry for the delayed response. There is a quick fix. When setting up the conda environment, change python=3.6 to python=3.8.

So, instead of:
`conda create -n pipits_env --channel bioconda --channel conda-forge --channel defaults python=3.6 pipits`

use:
`conda create -n pipits_env --channel bioconda --channel conda-forge --channel defaults python=3.8 pipits`

I have changed the instruction to reflect the change.

**Comment by ndusek** [comment]
@hsgweon, thank you for the quick response! I can confirm creating the environment with Python 3.8 resolves the `invalid syntax` error.
