### ISSUE TITLE
pipits 2 on mac

### ISSUE THREAD

**Issue by javiercnav** [hsgweon/pipits#9]
Hi there, I have installed pipits 2 on mac following all instructions in the site, and tested it using the raw data provided and i can't pass from pispino_seqprep step. See below. 
Any suggestions?
Bests

JCNavarro-M47:test_pipits jcnavarro$ source activate pipits_env
discarding //anaconda/bin from PATH
prepending //anaconda/envs/pipits_env/bin to PATH
(pipits_env)JCNavarro-M47:test_pipits jcnavarro$ pispino_createreadpairslist -i rawdata -o readpairslist.txt
Generating a read-pair list file from the input directory...
Done - "readpairslist.txt" created
(pipits_env)JCNavarro-M47:test_pipits jcnavarro$ pispino_seqprep -i rawdata -o out_seqprep -l readpairslist.txt
2018-03-28 15:42:35 pispino_seqprep started
2018-03-28 15:42:35 Checking listfile
2018-03-28 15:42:35 ... done
2018-03-28 15:42:35 Counting sequences in rawdata
Traceback (most recent call last):
  File "//anaconda/envs/pipits_env/bin/pispino_seqprep", line 203, in <module>
    verbose = options.verbose)
  File "//anaconda/envs/pipits_env/lib/python2.7/site-packages/pispino/seqprep.py", line 43, in count_sequences
    numberofsequences += int(getFileLineCount(input_dir  + "/" + filename, extensionType) / 4)
  File "//anaconda/envs/pipits_env/lib/python2.7/site-packages/pispino/seqtools.py", line 21, in getFileLineCount
    f = bz2.open(filename, "r")
AttributeError: 'module' object has no attribute 'open'

**Comment by hsgweon** [comment]
It appears that python2's bz2 module has no open command.

Can you please try to create a conda environment in python3 by:

conda create -n myNGSenv pispino python=3.6

and then: 

source activate myNGSenv

and try to run it again? Do let me know how you get on.

**Comment by javiercnav** [comment]
Hi there, I created the new environment which resulted in having pispino working on 1: pispino_createreadpairslist and 2: pispino_seqprep. However, the next step - the pipits_funits came as command not found. 

Seeing this I created a new environment in which I requested both pispino and pipits:
conda create -n myNGSenv2 pispino python=3.6 pipits

This seemed to work up to the point of pipits_process where I got the following:

(myNGSenv2)JCNavarro-M47:test_pipits jcnavarro$ pipits_process -i out_funits/ITS.fasta -o out_process
pipits_process 2.0, the PIPITS Project
https://github.com/hsgweon/pipits
---------------------------------

2018-03-29 11:05:39 pipits_process started
2018-03-29 11:05:39 Generating a sample list from the input sequences
2018-03-29 11:05:39 Dereplicating and removing unique sequences prior to picking OTUs
2018-03-29 11:05:39 Picking OTUs [VSEARCH]
2018-03-29 11:05:39 Removing chimeras [VSEARCH]
2018-03-29 11:05:43 Renaming OTUs
2018-03-29 11:05:43 Mapping reads onto centroids [VSEARCH]
2018-03-29 11:05:44 Making OTU table
2018-03-29 11:05:44 Converting classic tabular OTU into a BIOM format [BIOM]
2018-03-29 11:05:44 Error: None zero returncode: biom convert -i out_process/intermediate/otu_table_prelim.txt -o out_process/intermediate/otu_table_prelim.biom --table-type="OTU table" --to-json

**Comment by hsgweon** [comment]
Ok, can you possibly send me the output.log file from your pipits_process to h.s.gweon @ reading.ac.uk ? (remove spaces in the email)

**Comment by hsgweon** [comment]
(this seems to have been a problem relating conda package not finding the package and is to be resolved by looking at the page: https://conda.io/docs/user-guide/troubleshooting.html#conda-reports-that-a-package-is-installed-but-it-appears-not-to-be )

I will close this thread for now.
